### ISSUE TITLE
train problems

### ISSUE THREAD

**Issue by ZHZQJ** [jd730/EOPSN#2]
How to solve the problem of insufficient video memory? Thanks!

**Comment by jd730** [comment]
Hi @ZHZQJ , could you elaborate on the problem? I do not understand what is 'video' memory since this work is not related to video.

**Comment by ZHZQJ** [comment]
Hi @jd730 , Thank you for your reply, I'm sorry I didn't describe my problem clearly. The hardware resources are limited. After I used a smaller batch size, the gpu memory problem has been solved. Your work is great! Thanks!
