### ISSUE TITLE
About the pre-trained model.

### ISSUE THREAD

**Issue by GengDavid** [jd730/EOPSN#3]
Hi @jd730, thanks for sharing your wonderful work.
In the README, you said the training requires "void-suppression" pre-trained model. However, I find that in the config file, you still use the standard pre-trained model [here](https://github.com/jd730/EOPSN/blob/aadd6f6eba91d4ab4d91c7e3240fc45ff88b56c3/configs/EOPSN_K20.yaml#L5). 
If I want to train your EOPSN, which pre-trained model should I use?
Thx.

**Comment by jd730** [comment]
Hi @GengDavid,
Thank you for reporting it. 'void-suppression' pre-trained model is the correct one.

**Comment by GengDavid** [comment]
@jd730 Got it. Thanks for your reply. I have a further question about the 'void-suppression' pre-trained model. Does it mean pre-training the backbone model on ImageNet without the "Unknown" classes (i.e., using 1000-16=984 classes for pre-training)?

**Comment by jd730** [comment]
No, it is trained on COCO without unknown class and with suppression loss for void proposals: 
![image](https://user-images.githubusercontent.com/9247850/125056787-8e07b580-e0e3-11eb-8f34-a73113d3037e.png)
Please refer to the main paper for more details.

**Comment by GengDavid** [comment]
I see, thanks!
